### ISSUE TITLE
doesn't work at all

### ISSUE THREAD

**Issue by SuchSunset** [Solar-Tweaks/LunarSocket#10]
I've followed all the instructions and built the server and started it, but it just says listening on port 80

**Comment by JustAiden9** [comment]
Hey SuchSunset! Please Use Solar Tweaks To Use The Cosmetics. You, Will, Have To Go To The Patcher tab and then click Websocket. Lastly, You will type ws://localhost:80/connect while the Lunar Socket is Running. Then Boot up 1.8 and there you go.

**Comment by SuchSunset** [comment]
Thanks so much!

**Comment by JustAiden9** [comment]
Yep glad to help!
