### ISSUE TITLE
Connecting to mongo not working

### ISSUE THREAD

**Issue by Sarreos** [Solar-Tweaks/LunarSocket#19]
node_modules/mongodb-connection-string-url/lib/index.js:86
            throw new MongoParseError('Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"');

in my config the connection string starts with "mongodb://"

**Comment by Zone-Infinity** [comment]
Did u setup the mongo db?
U can either host it in local or use [Mongo Atlas]((https://www.mongodb.com/atlas)

**Comment by RichardDorian** [comment]
Can you maybe please probide your configuration file? (Don't forget to remove sensitive data such mongo password)

**Comment by Sarreos** [comment]
After the latest update the issue is fixed

**Comment by Sarreos** [comment]
> Did u setup the mongo db?
> U can either host it in local or use [Mongo Atlas](https://www.mongodb.com/atlas)

Yes I did
