### ISSUE TITLE
cape don't work

### ISSUE THREAD

**Issue by Sets0** [Solar-Tweaks/LunarSocket#20]
my cape don't work

**Comment by RichardDorian** [comment]
Hellom
What's your problem exactly?
Saying "my cape don't work" isn't really helpful

**Comment by Sets0** [comment]
https://user-images.githubusercontent.com/106275589/170500176-6e2f4a80-47cd-4d5b-a174-3c97850df04b.mp4

**Comment by NoCax** [comment]
> Lunarsocket.2.mp4

i have the same problem. (abbiamo palesemente guardato lo stesso video)

**Comment by Sets0** [comment]
https://user-images.githubusercontent.com/106275589/170510711-d8f94ef4-01e1-47fe-b026-5065ef14ae24.mp4

**Comment by Sets0** [comment]
@RichardDorian
