### ISSUE TITLE
API

### ISSUE THREAD

**Issue by TakenMC** [Solar-Tweaks/LunarSocket#28]
I was curious what the api option refers to and how to use it.
![image](https://user-images.githubusercontent.com/68560840/175938107-ff8d5c20-af3b-42f2-800c-815f4da9b12b.png)

**Comment by TinyWiFi** [comment]
The API Option refers to the new dashboard implementation from this commit [here](https://github.com/Solar-Tweaks/LunarSocket/commit/9f7fa25b54ff1122c50b0dab582c0e7dc17eea85)
