### ISSUE TITLE
Websocket keeps disconnecting

### ISSUE THREAD

**Issue by Sarreos** [Solar-Tweaks/LunarSocket#59]
![image](https://user-images.githubusercontent.com/47927259/200143536-18d7632c-51e3-49b4-ba57-31573d1af22e.png)

**Comment by RichardDorian** [comment]
Are you still getting the error?

**Comment by Sarreos** [comment]
Nope, it's gone.

**Comment by Sarreos** [comment]
Nope, it's gone.
