### ISSUE TITLE
API key lunar socket website ?

### ISSUE THREAD

**Issue by JustAiden9** [Solar-Tweaks/LunarSocket#62]
Hey, so I fixed my other issue but now I have a new one. I want to set up the lunar socket website and I just ran it like normal. It now asked me for an API key on the website, so I enter 'password'. When I type it in it says invalid key. Is there something else I should be typing in or looking for in a different config file?

**Comment by RadNotRed** [comment]
Idk if you still need help but you probably have API turned off.
