### ISSUE TITLE
 SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by Sarreos** [Solar-Tweaks/LunarSocket#84]
When I try to connect to the websocket this happends.
![image](https://user-images.githubusercontent.com/47927259/234038401-7b4f2c5a-1c40-4ffa-a078-912c454454b7.png)

**Comment by TBHGodPro** [comment]
It is a bug we are working on, will release a fix today, sorry about that.

**Comment by sharifjameel90** [comment]
> When I try to connect to the websocket this happends.
> ![image](https://user-images.githubusercontent.com/47927259/234038401-7b4f2c5a-1c40-4ffa-a078-912c454454b7.png)

dont create a storage.json your self name a file and leave it the code will create it self a storage.json it will work fine
